[project]
name="gene_viewer"
version="0.1.0"
requires-python = ">=3.10,<3.13"
authors = [
    { name="Simon Ament" }
]
description = "A lightweight and embeddable per-gene visualization of genomic regions, probes, and custom tracks."
dependencies = [
    "zstandard",
    "oligo_designer_toolsuite",
    "pybedtools",
    "biopython",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
